### ISSUE TITLE
Delegate function type for `SDL_EventFilter` (and others)

### ISSUE THREAD

**Issue by SaxxonPike** [ppy/SDL3-CS#104]
Firstly, let me express my gratitude for this project. Thank you for the best SDL3 bindings for C# today.

While I was using the SDL3-CS package, I discovered that the delegate types for callbacks (such as `SDL_AudioStreamCallback` and `SDL_EventFilter`) are not exposed in a way that is useful. For example, in order to use `SDL_EventFilter`, I must do this:

```
// assume 'filter' is a function that matches the delegate.
var delegatePtr = Marshal.GetFunctionPointerForDelegate(filter);
var functionPtr = (delegate*unmanaged[Cdecl]<IntPtr, SDL_Event*, int>)delegatePtr;
SDL_AddEventWatch(functionPtr, 0);
```

This works, but is rather cumbersome. The generated source for `SDL_AddEventWatch` is as follows, for reference:
```
public static extern int SDL_AddEventWatch([NativeTypeName("SDL_EventFilter")] delegate* unmanaged[Cdecl]<IntPtr, SDL_Event*, int> filter, [NativeTypeName("void*")] IntPtr userdata);
```
I think generating an overload and delegate function type here would make this much more useful. Ideally, we might generate overloads and delegate function types for other functions also.

Edit: I'm adding my delegate function definition here to illustrate what that might look like:
```
[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
public unsafe delegate int SDL_EventFilter(IntPtr userData, SDL_Event* ev);
```

**Comment by smoogipoo** [comment]
We do this in some cases, but it's currently a manual process, e.g. https://github.com/ppy/SDL3-CS/blob/master/SDL3-CS/SDL3/SDL_clipboard.cs

**Comment by smoogipoo** [comment]
In the case of `SDL_AddEventWatch` it's not really necessary because it's a callback. See our usage of it here:

https://github.com/ppy/osu-framework/blob/1eb26565dc7f3c4bd1c843a7e9d44227b95f069f/osu.Framework/Platform/SDL3/SDL3Window.cs#L232

https://github.com/ppy/osu-framework/blob/1eb26565dc7f3c4bd1c843a7e9d44227b95f069f/osu.Framework/Platform/SDL3/SDL3Window.cs#L331-L339

Which is about as good as it's ever going to be anyway.

**Comment by Susko3** [comment]
I suggest you use static methods annotated with [UnmanagedCallersOnlyAttribute](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.unmanagedcallersonlyattribute?view=net-8.0) as per smoogi's comment. If your event filter needs access to non-static data, make use of the `IntPtr userdata` param.

Delegate overloads are intentionally not available as they give the false sense that their memory is managed by the .NET GC.
Eg. if you don't store your `filter` delegate and the GC collects it, the next time SDL tries to call it, it'll burn and crash.

https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshal.getfunctionpointerfordelegate?view=net-8.0
> You must manually keep the delegate from being collected by the garbage collector from managed code. The garbage collector does not track references to unmanaged code.

To avoid this footgun, static methods are used - there's no dynamically allocated delegates, there's nothing for the GC to collect.
