### ISSUE TITLE
Add description to README

### ISSUE THREAD

**Issue by stanoddly** [ppy/SDL3-CS#141]
I happened to find this library via NuGet.org and I was actually surprised to find a full featured, functional SDL3 bindings. Great work!

I wonder, is it intentionally meant to be used by public? Or is it just a by-product of `osu!`?

Ultimately a few words in README would help to explain the intention.

**Comment by peppy** [comment]
This was created for our own usage primarily. We haven't completely migrated across to SDL3, either.

That said, it should be safe to use / consume elsewhere as long as you don't have huge expectations. We tend to only update the bindings when it suits us, but if you were to PR updates here in line with upstream SDL3 changes it would also more likely than not be accepted.

Adding a basic README is something we should do.
