### ISSUE TITLE
Android deploy failing

### ISSUE THREAD

**Issue by Susko3** [ppy/SDL3-CS#177]
The [android package](https://www.nuget.org/packages/ppy.SDL3-CS.Android) was not updated.

https://github.com/ppy/SDL3-CS/actions/runs/11884829681/job/33113585758#step:5:8

>  Error: C:\Program Files\dotnet\sdk\8.0.404\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(117,5): error **NETSDK1139: The target platform identifier android was not recognized.** [D:\a\SDL3-CS\SDL3-CS\SDL3-CS.Android\SDL3-CS.Android.csproj]
Error: C:\Program Files\dotnet\sdk\8.0.404\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(117,5): error **NETSDK1139: The target platform identifier android was not recognized.** [D:\a\SDL3-CS\SDL3-CS\SDL3-CS.Tests.Android\SDL3-CS.Tests.Android.csproj]

Not sure what's up with those errors, I can run `dotnet build SDL3-CS.Android.slnf -c Release` locally just fine.

**Comment by smoogipoo** [comment]
It's an intermittent issue at github's end: https://github.com/ppy/osu/pull/30747
